# Cell data for DF3
uint32 header_time  # only has second
uint32 dvl_time     # only has second
int16 num           # id of each cell data
float32 pos         # [m]
float32 v_x         # [m/s]
float32 v_y         # [m/s]
float32 v_z         # [m/s]
float32 v_z2        # [m/s]
uint8 amp1          # [dB]
uint8 amp2          # [dB]
uint8 amp3          # [dB]
uint8 amp4          # [dB]
uint8 cor1          # [%]
uint8 cor2          # [%]
uint8 cor3          # [%]
uint8 cor4          # [%]
