# Status for DF3
uint8 unused1        
uint8 bd_scaling        #Set bit indicates cm scaling of blanking distance
uint8 unused2        
uint8 unused3        
uint8 unused4        
uint8 echo_freq         #Echo Sounder Frequency Bin
uint8 boost_running     #Boost Running     
uint8 telemetry         #Telemetry data
uint8 echo_index        #Echo Sounder Index
uint8 active_config     #Active configuration
uint8 low_volt_skip     #Last measurement low voltage skip
uint8 prev_wakeup_state #Previous Wakeup State
uint8 auto_orien        #Auto orientation
uint8 orien             #Orientation
uint8 wakeup_state      #Wakeup State
