# Configuration for DF3, the current profile
uint8 pressure_valid   #Pressure sensor value valid
uint8 temp_valid       #Temperature sensor value valid
uint8 compass_valid    #Compass sensor values valid
uint8 tilt_valid       #Tilt sensor values valid
uint8 empty           
uint8 vel_exist        #Velocity data included
uint8 amp_exist        #Amplitude data included
uint8 cor_exist        #Correlation data included
uint8 alt_exist        #Altimeter data included
uint8 alt_raw_exist    #Altimeter Raw data included
uint8 ast_exist        #AST data included
uint8 echo_exist       #Echo Sounder data included
uint8 ahrs_exist       #AHRS data included
uint8 percentage_exist #Percentage Good data included
uint8 std_exist        #Std. Dev. data included
uint8 unused           