# Configuration for DF3, the current profile
uint8 pressure         
uint8 temp             
uint8 compass          
uint8 tilt             
uint8 empty           
uint8 velIncluded      
uint8 ampIncluded      
uint8 corrIncluded     
uint8 altiIncluded      
uint8 altiRawIncluded  
uint8 ASTIncluded      
uint8 echoIncluded     
uint8 ahrsIncluded     
uint8 PGoodIncluded    
uint8 stdDevIncluded   
uint8 unused          