test/nortek_dvl_node:
  ros__parameters:

    UDP:
      udp_rx: 9004
      udp_address: 192.168.2.110
      buffer_size: 512

    DVL:
      beam_angle: 25.0
      sound_speed: 1500.0
      fluid_density: 1023.0

    ROS:
      # frame id for twist msgs
      sensor_frame_id: "nortek_dvl"
      ## header frame for depth odometr msg.
      world_frame_id: "world"
      ## child frame for depth odometry msg.
      pressure_frame_id: "nortek_dvl_pressure"
      depth_cov: 0.001